import { NextRequest, NextResponse } from 'next/server';
import { createHash } from 'crypto';
import { findCase } from '@/lib/tracex/mock-data';
import { computeMetrics, detectCommunities } from '@/lib/tracex/centrality';
import { listEvidence, listAudit, mergeGraph, ACTOR, ensureCasesSeeded, logAudit } from '@/lib/tracex/server-utils';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const line = (char = '─', n = 78) => char.repeat(n);
const pad = (s: string, n: number) => (s.length > n ? s.slice(0, n - 1) + '…' : s.padEnd(n));

export async function GET(req: NextRequest) {
  const caseId = req.nextUrl.searchParams.get('caseId') || 'case-eagle-claw';
  const c = findCase(caseId);
  if (!c) {
    return NextResponse.json({ error: `Unknown caseId: ${caseId}` }, { status: 404 });
  }
  await ensureCasesSeeded();

  // Reconstruct the live graph (seed + every ingested exhibit) so the BSA
  // §63 report reflects the analyst's uploaded work, not just the static
  // seed. Mirrors /api/graph so the legal certificate and the dashboard
  // always agree on the same graph topology.
  const evidence = await listEvidence(c.id);
  const live = mergeGraph(c.nodes, c.edges, evidence);
  const audit = await listAudit(c.id);
  const now = new Date();
  const reportId = `TRACE-X-BSA63-${now.getFullYear()}-${String(now.getTime()).slice(-6)}`;

  const metrics = computeMetrics(live.nodes, live.edges);
  const communities = detectCommunities(live.nodes, live.edges);

  const ranked = [...live.nodes].sort((a, b) => metrics[b.id].riskScore - metrics[a.id].riskScore);
  const critical = ranked.filter((n) => metrics[n.id].riskScore >= 85);
  const totalFunds = live.edges.filter((e) => e.type === 'TRANSFERRED_FUNDS').reduce((s, e) => s + (e.weight ?? 0), 0);
  const totalCalls = live.edges.filter((e) => e.type === 'CALLED').reduce((s, e) => s + (e.weight ?? 0), 0);

  const parts: string[] = [];

  parts.push(line('═'));
  parts.push('  TRACE-X // ELECTRONIC EVIDENCE & INTELLIGENCE REPORT');
  parts.push('  Certificate under Section 63(4), Bharatiya Sakshya Adhiniyam, 2023');
  parts.push(line('═'));
  parts.push(`  REPORT ID      : ${reportId}`);
  parts.push(`  GENERATED (UTC): ${now.toISOString()}`);
  parts.push(`  GENERATED BY   : TRACE-X v2.4.1 — Criminal Intelligence Fusion Engine`);
  parts.push(`  OPERATOR       : ${ACTOR} (authenticated console session)`);
  parts.push(`  CLASSIFICATION : RESTRICTED // LAW ENFORCEMENT USE ONLY`);
  parts.push('');
  parts.push(line('─'));
  parts.push('1. CASE SUMMARY');
  parts.push(line('─'));
  parts.push(`  CASE ID   : ${c.id}`);
  parts.push(`  CODENAME  : ${c.codename}`);
  parts.push(`  AGENCY    : ${c.agency}`);
  parts.push(`  DESK      : ${c.desk}`);
  parts.push(`  STATUS    : ${c.status}`);
  parts.push(`  BRIEF     : ${c.summary}`);
  parts.push(`  GRAPH     : ${live.nodes.length} entities · ${live.edges.length} relationships · ${new Set(communities.values()).size} detected communities`);
  parts.push('');
  parts.push(line('─'));
  parts.push('2. SECTION 63(4) CERTIFICATE — ELECTRONIC RECORDS');
  parts.push(line('─'));
  parts.push('  I certify that the electronic records enumerated in Section 3 of this');
  parts.push('  report were produced by the TRACE-X fusion engine from computer');
  parts.push('  systems under lawful control of the investigating agency; that the');
  parts.push('  records were ingested in the ordinary course of intelligence');
  parts.push('  operations; and that each artefact is integrity-sealed with a');
  parts.push('  SHA-256 digest reproduced below, in accordance with Section 63 of');
  parts.push('  the Bharatiya Sakshya Adhiniyam, 2023.');
  parts.push('');
  parts.push(`  ${ACTOR} — Authorized Officer, ${c.agency}`);
  parts.push(`  Counter-signed electronically by TRACE-X Trust Service`);
  parts.push('');

  parts.push(line('─'));
  parts.push('3. EXHIBIT INVENTORY & CHAIN OF CUSTODY');
  parts.push(line('─'));
  if (evidence.length === 0) {
    parts.push('  (No ingested exhibits recorded for this case at time of export.)');
  } else {
    evidence.forEach((ev, i) => {
      parts.push(`  EXHIBIT E-${String(i + 1).padStart(2, '0')}`);
      parts.push(`    Filename      : ${ev.filename}`);
      parts.push(`    Type          : ${ev.fileType}`);
      parts.push(`    Size          : ${ev.sizeBytes.toLocaleString('en-IN')} bytes`);
      parts.push(`    Ingested (UTC): ${ev.ingestedAt}`);
      parts.push(`    SHA-256       : ${ev.sha256}`);
      parts.push(`    Entities      : ${ev.entityCount} extracted · ${ev.linkCount} links derived`);
      const custody = ev.custody.map((cu) => `${cu.event} @ ${cu.at} by ${cu.actor}`).join(' -> ');
      parts.push(`    Custody chain : ${custody}`);
      parts.push('');
    });
  }

  parts.push(line('─'));
  parts.push('4. ENTITY REGISTRY');
  parts.push(line('─'));
  parts.push(`  ${pad('ID', 16)}${pad('TYPE', 14)}${pad('LABEL', 26)}${pad('RISK', 6)}${pad('PR', 8)}${pad('BTW', 8)}FIRST SEEN`);
  for (const n of ranked) {
    const m = metrics[n.id];
    parts.push(`  ${pad(n.id, 16)}${pad(n.type, 14)}${pad(n.label, 26)}${pad(String(m.riskScore), 6)}${pad(m.pageRank.toFixed(4), 8)}${pad(m.betweenness.toFixed(4), 8)}${n.firstSeen}`);
  }
  parts.push('');
  parts.push(line('─'));
  parts.push('5. RELATIONSHIP LOG');
  parts.push(line('─'));
  const labelOf = (id: string) => live.nodes.find((n) => n.id === id)?.label ?? id;
  for (const e of [...live.edges].sort((a, b) => a.date.localeCompare(b.date))) {
    parts.push(`  ${e.date}  ${pad(labelOf(e.source), 24)} ──${pad(e.type, 20)}──> ${pad(labelOf(e.target), 24)}${e.label ? `[${e.label}]` : ''}`);
  }
  parts.push('');
  parts.push(line('─'));
  parts.push('6. NETWORK ANALYTICS SUMMARY');
  parts.push(line('─'));
  parts.push(`  Aggregate fund movement : ₹${(totalFunds / 100000).toFixed(1)} lakh across ${live.edges.filter((e) => e.type === 'TRANSFERRED_FUNDS').length} transfers`);
  parts.push(`  Aggregate call volume   : ${totalCalls} calls across ${live.edges.filter((e) => e.type === 'CALLED').length} CDR edges`);
  parts.push(`  Critical-risk entities  : ${critical.length}${critical.length ? ' — ' + critical.map((n) => n.label).join(', ') : ''}`);
  parts.push('');
  parts.push('  TOP-5 BY COMPOSITE RISK INDEX:');
  ranked.slice(0, 5).forEach((n, i) => {
    const m = metrics[n.id];
    parts.push(`    ${i + 1}. ${pad(n.label, 30)} risk ${m.riskScore} (${m.riskBand}) · PageRank ${m.pageRank.toFixed(4)} · betweenness ${m.betweenness.toFixed(4)} · degree ${m.degree}`);
  });
  parts.push('');
  parts.push(line('─'));
  parts.push('7. AUDIT TRAIL (CHAIN OF CUSTODY — SYSTEM EVENTS)');
  parts.push(line('─'));
  if (audit.length === 0) {
    parts.push('  (No system events recorded.)');
  } else {
    audit.slice(0, 30).forEach((a) => {
      parts.push(`  ${new Date(a.createdAt).toISOString()}  ${pad(a.action, 20)} ${a.actor} — ${a.detail}`);
    });
  }
  parts.push('');
  parts.push(line('─'));
  parts.push('8. ANALYST ASSESSMENT');
  parts.push(line('─'));
  const nTypes = live.nodes.reduce<Record<string, number>>((acc, n) => { acc[n.type] = (acc[n.type] ?? 0) + 1; return acc; }, {});
  const typeBreakdown = Object.entries(nTypes).map(([t, n]) => `${t}=${n}`).join(', ') || 'n/a';
  parts.push(`  The ${c.codename} network comprises ${live.nodes.length} entities (${typeBreakdown})`);
  parts.push(`  connected by ${live.edges.length} relationships. ${critical.length} critical-risk`);
  parts.push(`  node(s) surfaced at the apex of the composite TRACE-X risk index.`);
  parts.push(`  Community detection partitions the graph into ${new Set(communities.values()).size} compartment(s),`);
  parts.push(`  consistent with operational cell insulation where multiple clusters`);
  parts.push(`  are present. Aggregate fund movement across ${live.edges.filter((e) => e.type === 'TRANSFERRED_FUNDS').length} transfer edge(s)`);
  parts.push(`  totals ₹${(totalFunds / 100000).toFixed(1)} lakh; telephony analysis recorded ${totalCalls}`);
  parts.push(`  call events across ${live.edges.filter((e) => e.type === 'CALLED').length} CDR edge(s). Recommended action:`);
  parts.push('  simultaneous detention of critical nodes with parallel account freezes and IMEI blacklisting.');
  parts.push('');
  parts.push(line('─'));
  parts.push('9. INTEGRITY SEAL');
  parts.push(line('─'));
  const payload = JSON.stringify({ reportId, caseId: c.id, nodes: live.nodes.length, edges: live.edges.length, evidence: evidence.map((e) => e.sha256), generated: now.toISOString() });
  const seal = createHash('sha256').update(payload).digest('hex');
  parts.push(`  REPORT SHA-256 SEAL : ${seal}`);
  parts.push('  Any alteration to this report invalidates the seal. Verify against');
  parts.push('  the TRACE-X evidence registry before production before court.');
  parts.push('');
  parts.push(line('═'));
  parts.push('  END OF REPORT // TRACE-X // BSA 2023 §63 COMPLIANT');
  parts.push(line('═'));

  const body = parts.join('\n');
  await logAudit(c.id, 'REPORT_EXPORTED', `${reportId} — BSA §63 certificate generated (${body.length} bytes, seal ${seal.slice(0, 12)}…)`);

  return new NextResponse(body, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Content-Disposition': `attachment; filename="TRACE-X_${c.codename.replace(/\s+/g, '-')}_BSA63_Report.txt"`,
      'X-TraceX-Seal': seal,
    },
  });
}
